### ISSUE TITLE
[Bug]: Pending migration causing error after composer update

### ISSUE THREAD

**Issue by rtrudel** [Laravel-Lang/common#202] opened 2024-09-26 18:04 UTC
### Lang Package Name

laravel-lang/models

### Lang Package Version

6.4.0

### Laravel Framework Version

11.25.0

### PHP Version

8.2

### Dependencies
```
"require": {
        "php": "^8.2",
        "ext-intl": "*",
        "ext-zip": "*",
        "axlon/laravel-postal-code-validation": "^3.6",
        "bezhansalleh/filament-panel-switch": "^1.0",
        "bezhansalleh/filament-shield": "^3.2",
        "codeat3/blade-coolicons": "^1.5",
        "cviebrock/eloquent-sluggable": "^11.0",
        "filament/filament": "^3.2",
        "globalpayments/php-sdk": "^12.0",
        "internachi/modular": "^2.2",
        "jeffgreco13/filament-breezy": "^2.4",
        "joserick/laravel-livewire-discover": "^1.0",
        "laravel/framework": "^11.0",
        "laravel/horizon": "^5.27",
        "laravel/tinker": "^2.9",
        "livewire/flux": "^1.0",
        "livewire/flux-pro": "^1.0",
        "lorisleiva/laravel-actions": "^2.8",
        "owenvoke/blade-fontawesome": "^2.6",
        "pelmered/filament-money-field": "^1.2",
        "propaganistas/laravel-phone": "^5.3",
        "rawilk/laravel-settings": "^3.3",
        "ryangjchandler/blade-tabler-icons": "^2.3",
        "shuvroroy/filament-spatie-laravel-backup": "^2.2",
        "spatie/laravel-pdf": "^1.5",
        "spatie/laravel-permission": "^6.4",
        "spatie/laravel-translatable": "^6.6",
        "stechstudio/filament-impersonate": "^3.13",
        "stripe/stripe-php": "^15.7",
        "tomatophp/filament-users": "^1.0",
        "ysfkaya/filament-phone-input": "^2.3"
    },
    "require-dev": {
        "fakerphp/faker": "^1.23",
        "laravel-lang/common": "^6.2",
        "laravel/pint": "^1.13",
        "laravel/sail": "^1.29",
        "mockery/mockery": "^1.6",
        "nunomaduro/collision": "^8.0",
        "pestphp/pest": "^3.0",
        "pestphp/pest-plugin-drift": "^3.0",
        "spatie/laravel-error-solutions": "^1.0",
        "spatie/laravel-ignition": "^2.4"
    },
```

### Issue description

``` INFO  Running migrations.  

  2024_06_09_234306_create_translations_table .......................................................................................... 2.60ms FAIL

   ErrorException 

  Undefined property: LaravelLang\Config\Data\Shared\ModelsData::$connection

  at vendor/laravel-lang/models/database/migrations/2024_06_09_234306_create_translations_table.php:17
     13▕     public function up(): void
     14▕     {
     15▕         $config = $this->config();
     16▕ 
  ➜  17▕         Schema::connection($config->connection)->create($config->table, function (Blueprint $table) {
     18▕             $table->id();
     19▕ 
     20▕             $table->string('model_type', 255);
     21▕             $table->string('model_id', 255);

      +28 vendor frames 

  29  artisan:13
      Illuminate\Foundation\Application::handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))
```

### Steps to reproduce

`composer update`
doing some casual stuff in my app 
`php artisan migrate`

**Comment by andrey-helldar** [comment] 2024-09-26 18:54
@rtrudel, can you also show your localizations configuration file? It is located at the path “config/localization.php”.

**Comment by andrey-helldar** [comment] 2024-09-26 18:56
@rtrudel, that's it, don't. I found the reason. I'll fix it.

**Comment by rtrudel** [comment] 2024-09-26 18:56
Of course :-)

```php
<?php

declare(strict_types=1);

use LaravelLang\Config\Constants\RouteName;
use LaravelLang\LocaleList\Locale;

return [
    /*
     * Determines what type of files to use when updating language files.
     *
     * @see https://laravel-lang.com/configuration.html#inline
     *
     * By default, `false`.
     */

    'inline' => (bool) env('LOCALIZATION_INLINE', env('LANG_PUBLISHER_INLINE')),

    /*
     * Do arrays need to be aligned by keys before processing arrays?
     *
     * @see https://laravel-lang.com/configuration.html#alignment
     *
     * By default, true
     */

    'align' => (bool) env('LOCALIZATION_ALIGN', env('LANG_PUBLISHER_ALIGN', true)),

    /*
     * The language codes chosen for the files in this repository may not
     * match the preferences for your project.
     *
     * Specify here mappings of localizations with your project.
     *
     * @see https://laravel-lang.com/configuration.html#aliases
     */

    'aliases' => [
        // \LaravelLang\LocaleList\Locale::German->value => 'de-DE',
        // \LaravelLang\LocaleList\Locale::GermanSwitzerland->value => 'de-CH',
    ],

    /*
     * This option determines the mechanism for converting translation
     * keys into a typographic version.
     *
     * @see https://laravel-lang.com/configuration.html#smart_punctuation
     *
     * By default, false
     */

    'smart_punctuation' => [
        'enable' => (bool) env('LOCALIZATION_SMART_ENABLED', false),

        'common' => [
            'double_quote_opener' => '“',
            'double_quote_closer' => '”',
            'single_quote_opener' => '‘',
            'single_quote_closer' => '’',
        ],

        'locales' => [
            Locale::French->value => [
                'double_quote_opener' => '«&nbsp;',
                'double_quote_closer' => '&nbsp;»',
                'single_quote_opener' => '‘',
                'single_quote_closer' => '’',
            ],

            Locale::Russian->value => [
                'double_quote_opener' => '«',
                'double_quote_closer' => '»',
                'single_quote_opener' => '‘',
                'single_quote_closer' => '’',
            ],

            Locale::Ukrainian->value => [
                'double_quote_opener' => '«',
                'double_quote_closer' => '»',
                'single_quote_opener' => '‘',
                'single_quote_closer' => '’',
            ],

            Locale::Belarusian->value => [
                'double_quote_opener' => '«',
                'double_quote_closer' => '»',
                'single_quote_opener' => '‘',
                'single_quote_closer' => '’',
            ],
        ],
    ],

    /*
     * This option defines the application's route settings.
     *
     * @see https://laravel-lang.com/configuration.html#routes
     */

    'routes' => [
        /*
         * This option defines the settings for the key names used when working with application routing.
         *
         * Default values:
         *
         *   parameter - locale
         *   header    - Accept-Language
         *   cookie    - Accept-Language
         *   session   - Accept-Language
         *   column    - column
         */

        'names' => [
            'parameter' => RouteName::Parameter,
            'header'    => RouteName::Header,
            'cookie'    => RouteName::Cookie,
            'session'   => RouteName::Session,
            'column'    => RouteName::Column,
        ],

        /*
         * This option specifies the prefix of route group names.
         *
         * By default, `localized.`
         */

        'name_prefix' => env('LOCALIZATION_NAME_PREFIX', 'localized.'),

        /*
         * This option specifies the request redirection option when trying to open the default localization.
         *
         * Applies when using the `LaravelLang\Routes\Facades\LocalizationRoute` facade.
         */

        'redirect_default' => (bool) env('LOCALIZATION_REDIRECT_DEFAULT', false),
    ],

    /*
     * This option defines settings for working with model translations.
     *
     * @see https://laravel-lang.com/configuration.html#models
     */

    'models' => [
        /*
         * This option specifies a suffix for models containing translations.
         *
         * For example,
         *   main model is `App\Models\Page`
         *   translation model is `App\Models\PageTranslation`
         *
         * By default, `Translation`
         */

        'suffix' => 'Translation',

        /*
         * This option determines the need to filter localizations loaded
         * in the relay when using eager loading.
         *
         * By default, true.
         */

        'filter' => [
            'enabled' => (bool) env('LOCALIZATION_FILTER_ENABLED', true),
        ],

        /*
         * This option specifies a folder to store helper files for the IDE.
         *
         * By default, `vendor/_laravel_lang`
         */

        'helpers' => env('VENDOR_PATH', base_path('vendor/_laravel_lang')),
    ],

    /*
     * This option contains a list of translators that the Laravel Lang Translator project works with.
     *
     * Google Translate is enabled by default.
     *
     * @see https://laravel-lang.com/configuration.html#translators
     */

    'translators' => [
        /*
         * List of channels used for translations.
         *
         * By default,
         *
         *     Google is enabled
         *     Deepl  is disabled
         *     Yandex is disabled
         */

        'channels' => [
            'google' => [
                'translator' => '\LaravelLang\Translator\Integrations\Google',

                'enabled'  => (bool) env('TRANSLATION_GOOGLE_ENABLED', true),
                'priority' => (int) env('TRANSLATION_GOOGLE_PRIORITY', 1),
            ],

            'deepl' => [
                'translator' => '\LaravelLang\Translator\Integrations\Deepl',

                'enabled'  => (bool) env('TRANSLATION_DEEPL_ENABLED', false),
                'priority' => (int) env('TRANSLATION_DEEPL_PRIORITY', 2),

                'credentials' => [
                    'key' => (string) env('TRANSLATION_DEEPL_KEY'),
                ],
            ],

            'yandex' => [
                'translator' => '\LaravelLang\Translator\Integrations\Yandex',

                'enabled'  => (bool) env('TRANSLATION_YANDEX_ENABLED', false),
                'priority' => (int) env('TRANSLATION_YANDEX_PRIORITY', 3),

                'credentials' => [
                    'key'    => (string) env('TRANSLATION_YANDEX_KEY'),
                    'folder' => (string) env('TRANSLATION_YANDEX_FOLDER_ID'),
                ],
            ],
        ],

        'options' => [
            /*
             * Set a custom pattern for extracting replaceable keywords from the string,
             * default to extracting words prefixed with a colon.
             *
             *  Available options:
             *
             *     `true` is a `/:(\w+)/`
             *     `false` will disable regular expression processing
             *      `/any regex/` - any regular expression you specify
             *
             *   By default, `true`
             *
             * @example (e.g. "Hello :name" will extract "name")
             */

            'preserve_parameters' => true,
        ],
    ],
];

```

**Comment by andrey-helldar** [comment] 2024-09-26 19:02
@rtrudel, I realized what the problem is - you have `laravel-lang/models` version `v1.0-ALPHA1` installed. It was in it that you had this very migration file. There have been several more releases since then.

Can you run the console command `composer info laravel-lang/models` to make sure?

For example:
```bash
$ composer info laravel-lang/models
name     : laravel-lang/models
descrip. : Easy and fast way to localize models
keywords : database, l18n, languages, laravel, locales, localization, models, translate, translations
versions : * 1.1.0
```

**Comment by rtrudel** [comment] 2024-09-26 19:19
`$ composer info laravel-lang/models`
```
name     : laravel-lang/models
descrip. : Easy and fast way to localize models
keywords : database, l18n, languages, laravel, locales, localization, models, translate, translations
versions : * v1.0-ALPHA1
```

`$ composer why laravel-lang/models`
```
laravel-lang/common 6.4.0 requires laravel-lang/models (^1.0) 
```
and why not dig the rabbit hole a bit more...
`$ composer why laravel-lang/common`
```
laravel/laravel dev-main requires (for development) laravel-lang/common (^6.2) 
```

**Comment by andrey-helldar** [comment] 2024-09-26 19:28
@rtrudel, I found a solution to your problem.

The reason is that the value of the `minimum-stability` parameter is not set as `stable`. This action has been [recommended](https://laravel.com/docs/10.x/upgrade#updating-minimum-stability) since Laravel 10.

To check, I changed the value of the parameter to `dev` and saw that my application installs DEV versions of dependencies, among them `laravel-lang/models` version `v1.0-ALPHA1`:

<details>
<summary>Install dependencies as DEV mode</summary>

```bash
  - Installing pestphp/pest-plugin (3.x-dev e79b26c): Extracting archive
  - Installing voku/portable-ascii (2.0.1): Extracting archive
  - Installing symfony/polyfill-php80 (1.x-dev 60328e3): Extracting archive
  - Installing symfony/polyfill-mbstring (1.x-dev 2369cb9): Extracting archive
  - Installing symfony/polyfill-ctype (1.x-dev a3cc8b0): Extracting archive
  - Installing phpoption/phpoption (dev-master e3fac8b): Extracting archive
  - Installing graham-campbell/result-type (1.1.x-dev 3ba905c): Extracting archive
  - Installing vlucas/phpdotenv (dev-master a59a137): Extracting archive
  - Installing symfony/css-selector (7.2.x-dev 601a5ce): Extracting archive
  - Installing tijsverkoyen/css-to-inline-styles (dev-master 97b4134): Extracting archive
  - Installing symfony/var-dumper (7.2.x-dev e3f3cd6): Extracting archive
  - Installing symfony/polyfill-uuid (1.x-dev 21533be): Extracting archive
  - Installing symfony/uid (7.2.x-dev 2d294d0): Extracting archive
  - Installing symfony/deprecation-contracts (dev-main 0e0d29c): Extracting archive
  - Installing symfony/routing (7.2.x-dev 35fb8cb): Extracting archive
  - Installing symfony/process (7.2.x-dev 2ad775b): Extracting archive
  - Installing symfony/polyfill-php83 (1.x-dev 2fb86d6): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (1.x-dev 3833d72): Extracting archive
  - Installing symfony/polyfill-intl-idn (1.x-dev 9614ac4): Extracting archive
  - Installing symfony/mime (7.2.x-dev fb61771): Extracting archive
  - Installing psr/container (dev-master 7079847): Extracting archive
  - Installing symfony/service-contracts (dev-main bd1d9e5): Extracting archive
  - Installing psr/event-dispatcher (dev-master bbd9eac): Extracting archive
  - Installing symfony/event-dispatcher-contracts (dev-main 8f93aec): Extracting archive
  - Installing symfony/event-dispatcher (7.2.x-dev 910c5db): Extracting archive
  - Installing psr/log (dev-master f16e1d5): Extracting archive
  - Installing doctrine/lexer (3.1.x-dev 042e47e): Extracting archive
  - Installing egulias/email-validator (4.x-dev b4a1a0e): Extracting archive
  - Installing symfony/mailer (7.2.x-dev 7b16156): Extracting archive
  - Installing symfony/http-foundation (7.2.x-dev 8e61eab): Extracting archive
  - Installing symfony/error-handler (7.2.x-dev 95d878c): Extracting archive
  - Installing symfony/http-kernel (7.2.x-dev 2d4a4cc): Extracting archive
  - Installing symfony/finder (7.2.x-dev afa87bc): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (1.x-dev b912392): Extracting archive
  - Installing symfony/string (7.2.x-dev 7e9bd70): Extracting archive
  - Installing symfony/console (7.2.x-dev dbccd36): Extracting archive
  - Installing ramsey/collection (2.0.0): Extracting archive
  - Installing brick/math (0.12.1): Extracting archive
  - Installing ramsey/uuid (4.x-dev 7839a56): Extracting archive
  - Installing psr/simple-cache (dev-master 2d280c2): Extracting archive
  - Installing nunomaduro/termwind (2.x-dev e5f21ea): Extracting archive
  - Installing symfony/translation-contracts (dev-main b9d2189): Extracting archive
  - Installing symfony/translation (7.2.x-dev b0e6bcd): Extracting archive
  - Installing psr/clock (1.0.0): Extracting archive
  - Installing symfony/clock (7.2.x-dev b81435f): Extracting archive
  - Installing carbonphp/carbon-doctrine-types (dev-main 9098d1c): Extracting archive
  - Installing nesbot/carbon (dev-master 4c21a97): Extracting archive
  - Installing monolog/monolog (dev-main 3327c29): Extracting archive
  - Installing league/mime-type-detection (1.16.0): Extracting archive
  - Installing league/flysystem (3.x-dev 22af5a3): Extracting archive
  - Installing league/flysystem-local (3.x-dev e0e8d52): Extracting archive
  - Installing nette/utils (dev-master 736c567): Extracting archive
  - Installing nette/schema (v1.3.x-dev 9ff5667): Extracting archive
  - Installing dflydev/dot-access-data (dev-main a23a2bf): Extracting archive
  - Installing league/config (dev-main 708b872): Extracting archive
  - Installing league/commonmark (dev-main bbef330): Extracting archive
  - Installing laravel/serializable-closure (dev-master 43244bf): Extracting archive
  - Installing laravel/framework (11.x-dev 0d78422): Extracting archive
  - Installing laravel/prompts (v0.2.1): Extracting archive
  - Installing guzzlehttp/uri-template (1.0.x-dev cbc8960): Extracting archive
  - Installing psr/http-message (dev-master 402d35b): Extracting archive
  - Installing psr/http-client (dev-master bb5906e): Extracting archive
  - Installing ralouphie/getallheaders (3.0.3): Extracting archive
  - Installing psr/http-factory (1.1.0): Extracting archive
  - Installing guzzlehttp/psr7 (2.7.x-dev a70f5c9): Extracting archive
  - Installing guzzlehttp/promises (2.0.x-dev 6ea8dd0): Extracting archive
  - Installing guzzlehttp/guzzle (7.9.x-dev d281ed3): Extracting archive
  - Installing fruitcake/php-cors (v1.3.0): Extracting archive
  - Installing webmozart/assert (1.11.0): Extracting archive
  - Installing dragonmantank/cron-expression (dev-master e418256): Extracting archive
  - Installing doctrine/inflector (2.1.x-dev f587d8c): Extracting archive
  - Installing anourvalar/eloquent-serialize (1.2.25): Extracting archive
  - Installing axlon/laravel-postal-code-validation (3.x-dev 20b5483): Extracting archive
  - Installing spatie/laravel-package-tools (1.16.5): Extracting archive
  - Installing masterminds/html5 (2.9.0): Extracting archive
  - Installing league/uri-interfaces (dev-master 48e741e): Extracting archive
  - Installing league/uri (dev-master eb091b8): Extracting archive
  - Installing symfony/html-sanitizer (7.2.x-dev 1d23de4): Extracting archive
  - Installing spatie/invade (2.1.0): Extracting archive
  - Installing spatie/color (1.6.0): Extracting archive
  - Installing ryangjchandler/blade-capture-directive (v1.0.0): Extracting archive
  - Installing livewire/livewire (v3.5.4): Extracting archive
  - Installing kirschbaum-development/eloquent-power-joins (3.5.8): Extracting archive
  - Installing psr/cache (dev-master 0a7c67d): Extracting archive
  - Installing doctrine/deprecations (1.1.x-dev dfbaa3c): Extracting archive
  - Installing doctrine/dbal (4.2.x-dev 0e81fa2): Extracting archive
  - Installing blade-ui-kit/blade-icons (1.x-dev 1211cda): Extracting archive
  - Installing blade-ui-kit/blade-heroicons (2.4.0): Extracting archive
  - Installing filament/support (3.x-dev 2183eb1): Extracting archive
  - Installing filament/widgets (3.x-dev 06b70c4): Extracting archive
  - Installing openspout/openspout (4.x-dev 0950b6b): Extracting archive
  - Installing league/csv (dev-master 4d05533): Extracting archive
  - Installing filament/actions (3.x-dev 4cf93bf): Extracting archive
  - Installing filament/notifications (3.x-dev 03ea56e): Extracting archive
  - Installing filament/infolists (3.x-dev dd6e231): Extracting archive
  - Installing filament/forms (3.x-dev 46a42db): Extracting archive
  - Installing danharrin/date-format-converter (v0.3.1): Extracting archive
  - Installing filament/tables (3.x-dev 75acf6f): Extracting archive
  - Installing danharrin/livewire-rate-limiting (v1.3.1): Extracting archive
  - Installing filament/filament (3.x-dev 8d28c97): Extracting archive
  - Installing bezhansalleh/filament-panel-switch (1.0.6): Extracting archive
  - Installing spatie/laravel-permission (dev-main 05f620c): Extracting archive
  - Installing bezhansalleh/filament-shield (3.x-dev 937072f): Extracting archive
  - Installing sebastian/environment (dev-main e4588b2): Extracting archive
  - Installing sebastian/version (dev-main 4e4fe61): Extracting archive
  - Installing sebastian/type (dev-main 21b95e1): Extracting archive
  - Installing sebastian/recursion-context (dev-main 76780b2): Extracting archive
  - Installing sebastian/object-reflector (dev-main 1acd959): Extracting archive
  - Installing sebastian/object-enumerator (dev-main 0bdb59b): Extracting archive
  - Installing sebastian/global-state (dev-main 633c9ba): Extracting archive
  - Installing sebastian/exporter (dev-main 575f0d2): Extracting archive
  - Installing sebastian/diff (dev-main b8899d8): Extracting archive
  - Installing sebastian/comparator (dev-main fa37b9e): Extracting archive
  - Installing sebastian/code-unit (dev-main 8c846a9): Extracting archive
  - Installing sebastian/cli-parser (dev-main b9d804c): Extracting archive
  - Installing phpunit/php-timer (dev-main bb05128): Extracting archive
  - Installing phpunit/php-text-template (dev-main b7122ac): Extracting archive
  - Installing phpunit/php-invoker (dev-main 1dd1db7): Extracting archive
  - Installing phpunit/php-file-iterator (dev-main 4d2f732): Extracting archive
  - Installing theseer/tokenizer (1.2.3): Extracting archive
  - Installing nikic/php-parser (v5.2.0): Extracting archive
  - Installing sebastian/lines-of-code (dev-main 84427eb): Extracting archive
  - Installing sebastian/complexity (dev-main ff87283): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (dev-main fa0fbdb): Extracting archive
  - Installing phpunit/php-code-coverage (dev-main 8032a53): Extracting archive
  - Installing phar-io/version (3.2.1): Extracting archive
  - Installing phar-io/manifest (dev-master 54750ef): Extracting archive
  - Installing myclabs/deep-copy (1.x-dev 3a6b9a4): Extracting archive
  - Installing phpunit/phpunit (11.3.6): Extracting archive
  - Installing jean85/pretty-package-versions (2.x-dev d2ed36b): Extracting archive
  - Installing fidry/cpu-core-counter (1.2.0): Extracting archive
  - Installing brianium/paratest (7.x-dev 9964b69): Extracting archive
  - Installing codeat3/blade-coolicons (1.5.0): Extracting archive
  - Installing composer/ca-bundle (dev-main 48a7928): Extracting archive
  - Installing composer/metadata-minifier (dev-main 20554d4): Extracting archive
  - Installing composer/spdx-licenses (dev-main 614a1b8): Extracting archive
  - Installing composer/pcre (dev-main 63aaeac): Extracting archive
  - Installing composer/xdebug-handler (3.0.5): Extracting archive
  - Installing cocur/slugify (v4.6.0): Extracting archive
  - Installing cviebrock/eloquent-sluggable (dev-master 0f501d5): Extracting archive
  - Installing dasprid/enum (1.0.6): Extracting archive
  - Installing dragon-code/contracts (2.x-dev 59c93e7): Extracting archive
  - Installing fakerphp/faker (1.23.x-dev 4dae775): Extracting archive
  - Installing giggsey/libphonenumber-for-php-lite (8.13.46): Extracting archive
  - Installing globalpayments/php-sdk (12.0.9): Extracting archive
  - Installing symfony/polyfill-php81 (1.x-dev 4a4cfc2): Extracting archive
  - Installing symfony/polyfill-php73 (1.x-dev 0f68c03): Extracting archive
  - Installing symfony/filesystem (7.2.x-dev edd9588): Extracting archive
  - Installing seld/signal-handler (dev-main 606a192): Extracting archive
  - Installing seld/phar-utils (1.2.1): Extracting archive
  - Installing seld/jsonlint (1.11.0): Extracting archive
  - Installing react/promise (3.x-dev 8a16464): Extracting archive
  - Installing justinrainbow/json-schema (5.x-dev feb2ca6): Extracting archive
  - Installing composer/semver (dev-main 4313d26): Extracting archive
  - Installing composer/class-map-generator (dev-main 465b1b0): Extracting archive
  - Installing composer/composer (dev-main 95b9b54): Extracting archive
  - Installing internachi/modular (2.2.0): Extracting archive
  - Installing paragonie/constant_time_encoding (v3.0.0): Extracting archive
  - Installing pragmarx/google2fa (8.x-dev 0f60738): Extracting archive
  - Installing bacon/bacon-qr-code (v3.0.0): Extracting archive
  - Installing jeffgreco13/filament-breezy (2.x-dev 93baeb6): Extracting archive
  - Installing joserick/laravel-livewire-discover (v1.0.0): Extracting archive
  - Installing dragon-code/support (6.x-dev c1e9868): Extracting archive
  - Installing laravel-lang/native-locale-names (2.x-dev 7d51afc): Extracting archive
  - Installing laravel-lang/native-currency-names (1.x-dev 00fa6e8): Extracting archive
  - Installing laravel-lang/native-country-names (1.x-dev 3a79acb): Extracting archive
  - Installing archtechx/enums (v1.1.0): Extracting archive
  - Installing laravel-lang/locale-list (1.x-dev 53be035): Extracting archive
  - Installing laravel-lang/config (1.x-dev aca8d6e): Extracting archive
  - Installing laravel-lang/locales (2.x-dev c0d565e): Extracting archive
  - Installing laravel-lang/routes (1.x-dev 644c389): Extracting archive
  - Installing dragon-code/pretty-array (4.x-dev 40c3a45): Extracting archive
  - Installing laravel-lang/publisher (16.x-dev 7e0a6ea): Extracting archive
  - Installing laravel-lang/models (v1.0-ALPHA1): Extracting archive
  - Installing laravel-lang/lang (15.7.5): Extracting archive
  - Installing laravel-lang/json-fallback (2.x-dev 6274019): Extracting archive
  - Installing laravel-lang/http-statuses (3.x-dev 15d9120): Extracting archive
  - Installing laravel-lang/attributes (2.x-dev 4fa0e7e): Extracting archive
  - Installing laravel-lang/actions (1.x-dev e9c7a50): Extracting archive
  - Installing laravel-lang/common (6.x-dev a6d1bea): Extracting archive
  - Installing laravel/pint (v1.18.1): Extracting archive
  - Installing symfony/yaml (7.2.x-dev 888f0ea): Extracting archive
  - Installing laravel/sail (1.x-dev 2c7c336): Extracting archive
  - Installing psy/psysh (dev-main 7ad43b6): Extracting archive
  - Installing laravel/tinker (2.x-dev 8aa2522): Extracting archive
  - Installing livewire/flux (v1.0.2): Extracting archive
  - Installing lorisleiva/lody (v0.5.0): Extracting archive
  - Installing lorisleiva/laravel-actions (v2.8.4): Extracting archive
  - Installing hamcrest/hamcrest-php (dev-master dd03e52): Extracting archive
  - Installing mockery/mockery (1.7.x-dev 3f8d3ff): Extracting archive
  - Installing filp/whoops (2.16.0): Extracting archive
  - Installing nunomaduro/collision (v8.x-dev efb38f7): Extracting archive
  - Installing thecodingmachine/safe (v2.5.0): Extracting archive
  - Installing owenvoke/blade-fontawesome (v2.6.0): Extracting archive
  - Installing moneyphp/money (v4.5.0): Extracting archive
  - Installing pelmered/filament-money-field (1.4.1): Extracting archive
  - Installing phpstan/phpdoc-parser (1.32.0): Extracting archive
  - Installing phpdocumentor/reflection-common (dev-master a0eeab5): Extracting archive
  - Installing phpdocumentor/type-resolver (1.x-dev eee054a): Extracting archive
  - Installing phpdocumentor/reflection-docblock (5.x-dev 60741fe): Extracting archive
  - Installing ta-tikoma/phpunit-architecture-test (0.8.4): Extracting archive
  - Installing pestphp/pest-plugin-arch (3.x-dev 0a27e55): Extracting archive
  - Installing pestphp/pest-plugin-mutate (3.x-dev e10dbdc): Extracting archive
  - Installing pestphp/pest (3.x-dev 4e2987d): Extracting archive
  - Installing pestphp/pest-plugin-drift (3.x-dev cd506d2): Extracting archive
  - Installing rawilk/laravel-settings (v3.3.1): Extracting archive
  - Installing ryangjchandler/blade-tabler-icons (v2.3.0): Extracting archive
  - Installing spatie/temporary-directory (2.2.1): Extracting archive
  - Installing spatie/laravel-signal-aware-command (2.0.0): Extracting archive
  - Installing spatie/db-dumper (3.7.0): Extracting archive
  - Installing spatie/laravel-backup (9.1.1): Extracting archive
  - Installing calebporzio/sushi (v2.5.2): Extracting archive
  - Installing shuvroroy/filament-spatie-laravel-backup (v2.2.2): Extracting archive
  - Installing spatie/backtrace (1.6.2): Extracting archive
  - Installing spatie/flare-client-php (1.8.0): Extracting archive
  - Installing spatie/error-solutions (1.1.1): Extracting archive
  - Installing spatie/laravel-error-solutions (1.0.0): Extracting archive
  - Installing spatie/ignition (1.15.0): Extracting archive
  - Installing spatie/laravel-ignition (2.8.0): Extracting archive
  - Installing spatie/browsershot (4.3.0): Extracting archive
  - Installing spatie/laravel-pdf (1.5.2): Extracting archive
  - Installing spatie/laravel-translatable (6.8.0): Extracting archive
  - Installing lab404/laravel-impersonate (1.7.5): Extracting archive
  - Installing stechstudio/filament-impersonate (3.14): Extracting archive
  - Installing stripe/stripe-php (v15.11.0-beta.1): Extracting archive
  - Installing tomatophp/console-helpers (v1.1.0): Extracting archive
  - Installing tomatophp/filament-users (v1.0.12): Extracting archive
  - Installing propaganistas/laravel-phone (5.3.2): Extracting archive
  - Installing ysfkaya/filament-phone-input (2.x-dev 86eb648): Extracting archive
```
</details>

## Solution

### Option 1

If you need a stable environment, I recommend replacing the value of the `minimum-stability` property in the `composer.json` file with `stable` and running the `composer update` console command. But in this case you will have to fix the version of the `pestphp/pest-plugin-drift` plugin to `^2.0` (it is currently listed as `^3.0` - this is an unstable version). And, after that, fix the other versions as well:

```diff
 "require-dev": {
    "fakerphp/faker": "^1.23",
    "laravel-lang/common": "^6.2",
    "laravel/pint": "^1.13",
    "laravel/sail": "^1.29",
    "mockery/mockery": "^1.6",
    "nunomaduro/collision": "^8.0",
-   "pestphp/pest": "^3.0",
-   "pestphp/pest-plugin-drift": "^3.0",
+   "pestphp/pest": "^2.0",
+   "pestphp/pest-plugin-drift": "^2.0",
    "spatie/laravel-error-solutions": "^1.0",
    "spatie/laravel-ignition": "^2.4"
 },
```

### Option 2

If you need these dev dependencies, then explicitly specify the version `“laravel-lang/models”: “^1.1” in the `composer.json` file:

```diff
 "require-dev": {
    "fakerphp/faker": "^1.23",
    "laravel-lang/common": "^6.4",
+    "laravel-lang/models": "^1.1",
    "laravel/pint": "^1.13",
    "laravel/sail": "^1.29",
    "mockery/mockery": "^1.6",
    "nunomaduro/collision": "^8.0",
    "pestphp/pest": "^3.0",
    "pestphp/pest-plugin-drift": "^3.0",
    "spatie/laravel-error-solutions": "^1.0",
    "spatie/laravel-ignition": "^2.4"
 },
```

After that, run the `composer update` console command.

But note that because of the `minimum-stablility` parameter, the `dev` versions of all packages including `Laravel Lang: Models` will also be installed. But this time a fresh version from the `1.x` branch will be installed.

**Comment by andrey-helldar** [comment] 2024-09-26 19:31
I don't know why, but Composer chose to install the ALPHA version of the package even though the `minimum-stability` parameter specifies `dev` (at least that's how I specified it for mine). This setting should have installed the `dev` version, not the `alpha` version. After all, to install `alpha` you have to specify - pay attention - `alpha`....

**Comment by rtrudel** [comment] 2024-09-26 19:41
Thank you!

In the end, I just had to remove `pestphp/pest-plugin-drift`(qhich I don't need... I guess...) while keeping `pestphp/pest` at version 3.x, which is stable since few weeks I think. 

```diff
"pestphp/pest": "^3.0",
- "pestphp/pest-plugin-drift": "^3.0"
```

I also reinstalled `laravel-lang/common`, and there are no more pending migrations. 

```diff
+ "laravel-lang/common": "^6.3"
```

**Comment by andrey-helldar** [comment] 2024-09-26 20:18
Pest 3 was set for release on September 9th. The `pestphp/pest-plugin-drift` plugin does not support it yet.

It is possible to downgrade the Laravel Lang Common version, but there is no point - the version is listed as `^6.3`, which means that calling the `composer update` console command will install the latest version from line 6. At the moment it is `6.4`.

Also, I still recommend setting the `"minimum-stablility": "stable"` parameter in the `composer.json` file and run the `composer update` console command after that.

**Closed by andrey-helldar** 2024-09-26 20:18 UTC
Labels: bug, common
